services:
  # Shared DB
  database:
    image: postgres:15-alpine
    container_name: messaging-db
    environment:
      POSTGRES_DB: messaging
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_user -d messaging"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Message Queue
  # rabbitmq:
  #   image: rabbitmq:3-management
  #   ports:
  #     - "5672:5672"    # server
  #     - "15672:15672"  # web UI
  #   environment:
  #     RABBITMQ_DEFAULT_USER: user
  #     RABBITMQ_DEFAULT_PASS: password
    # healthcheck:
    #   test: rabbitmq-diagnostics -q ping
    #   interval: 10s
    #   timeout: 10s
    #   retries: 5

  # API Gateway Service (FastAPI routing)
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: messaging-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://db_user:db_password@database:5432/messaging
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672/
    volumes:
      - ./src:/app/src
    depends_on:
      database:
        condition: service_healthy
      # rabbitmq:
      #   condition: service_started
    restart: unless-stopped


volumes:
  postgres_data: